version: '3.7'
services:
    postgres:
        image: postgres:9.6
        container_name: airflow_db
        volumes:
            - ./postgres:/var/lib/postgresql/real-time-traffic
        env_file:
            - .env


    webserver:
        image: jcarless/real-time-traffic:latest
        container_name: airflow
        build: ./
        restart: always
        depends_on:
            - postgres
        env_file:
            - .env

        volumes:
            - /Users/jerome/Documents/traffic-data-dags:/usr/local/airflow/dags
            - ./credentials:/usr/local/credentials
            - ./config:/usr/local/airflow/config
            - ./script:/usr/local/airflow/script
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3